export const  USER_LOGIN_REQUEST=  "USER_LOGIN_REQUEST"
export const  USER_LOGIN_SUCCESS=  "USER_LOGIN_SUCCESS"
export const  USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"


export const  USER_SIGNUP_REQUEST=  "USER_SIGNUP_REQUEST"
export const  USER_SIGNUP_SUCCESS=  "USER_SIGNUP_SUCCESS"
export const  USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const  ADMIN_REQUEST=  "ADMIN_REQUEST"
export const  ADMIN_SUCCESS=  "ADMIN_SUCCESS"
export const ADMIN_FAIL = "ADMIN_FAIL"
